In [1]:
import numpy as np
x = np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [1]:
%timeit [j**4 for j in range(1,9)]

828 ns ± 35.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [3]:
import numpy as np

%timeit np.arange(1,9)**4

1.13 μs ± 16.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [3]:
import numpy as np
a = np.array([1,2,3,4])
print(a)
print(type(a))
print(a.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [2]:
import numpy as np
l = []
for i in range(1,5):
    x = int(input("Enter the number:"))
    l.append(x)

print(np.array(l))

[1 2 3 4]


In [4]:
import numpy as np
ar = np.array([[1,2,3,4],[4,3,2,1]])
print(ar)
print(ar.ndim)

[[1 2 3 4]
 [4 3 2 1]]
2


In [6]:
import numpy as np
ar2 = np.array([[[1,2],[2,3],[3,4]],[[4,5],[5,6],[6,7]],[[8,9],[8,6],[6,5]]])
print(ar2)
print(ar2.ndim)

[[[1 2]
  [2 3]
  [3 4]]

 [[4 5]
  [5 6]
  [6 7]]

 [[8 9]
  [8 6]
  [6 5]]]
3
