In [1]:
import numpy as np
x = np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [1]:
%timeit [j**4 for j in range(1,9)]

828 ns ± 35.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [3]:
import numpy as np

%timeit np.arange(1,9)**4

1.13 μs ± 16.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [3]:
import numpy as np
a = np.array([1,2,3,4])
print(a)
print(type(a))
print(a.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [2]:
import numpy as np
l = []
for i in range(1,5):
    x = int(input("Enter the number:"))
    l.append(x)

print(np.array(l))

[1 2 3 4]


In [4]:
import numpy as np
ar = np.array([[1,2,3,4],[4,3,2,1]])
print(ar)
print(ar.ndim)

[[1 2 3 4]
 [4 3 2 1]]
2


In [6]:
import numpy as np
ar2 = np.array([[[1,2],[2,3],[3,4]],[[4,5],[5,6],[6,7]],[[8,9],[8,6],[6,5]]])
print(ar2)
print(ar2.ndim)

[[[1 2]
  [2 3]
  [3 4]]

 [[4 5]
  [5 6]
  [6 7]]

 [[8 9]
  [8 6]
  [6 5]]]
3


In [4]:
import numpy as np
var = np.random.rand(4)
print(var)

[0.0766609  0.67920605 0.85871239 0.6064972 ]


In [7]:
var1 = np.random.rand(2,5)
print(var1)

[[0.87467987 0.86961874 0.88307764 0.25048585 0.2477838 ]
 [0.49361626 0.40967859 0.96229619 0.39543135 0.41720222]]


In [14]:
var2 = np.random.randn(5)
print(var2)

[ 1.24691659 -1.12323554  0.83146043  0.82432783 -0.91254147]


In [15]:
var3 = np.random.ranf(6)
print(var3)

[0.38015604 0.93350019 0.81752289 0.2173538  0.64223122 0.84396596]


In [17]:
var4 = np.random.randint(5,20,5)
print(var4)

[13 17 11  6 14]
