In [44]:
import numpy as np

In [45]:
np.random.random()

0.5331652849730171

In [46]:
np.random.seed(1)
np.random.random()

0.417022004702574

In [47]:
np.random.uniform(3,100)

72.87147586388933

In [48]:
np.random.uniform(1,100,10).reshape(2,5)

array([[ 1.01132311, 30.93092469, 15.52883319, 10.14152088, 19.43976093],
       [35.21051198, 40.27997995, 54.34285667, 42.50025693, 68.83673054]])

In [49]:
np.random.randint(1,10)

3

In [50]:
r = np.random.randint(1,10,15).reshape(5,3)
r

array([[5, 8, 8],
       [2, 8, 1],
       [7, 8, 7],
       [2, 1, 2],
       [9, 9, 4]], dtype=int32)

In [51]:
a= np.random.randint(1,10,6).reshape(6)
a

array([9, 8, 4, 7, 6, 2], dtype=int32)

In [52]:
np.max(a)

np.int32(9)

In [56]:
np.argmax(a)

np.int64(0)

In [53]:
a[np.argmax(a)]

np.int32(9)

In [54]:
np.min(a)

np.int32(2)

In [57]:
np.argmin(a)

np.int64(5)

In [55]:
a[np.argmin(a)]

np.int32(2)

In [58]:
a= np.random.randint(1,10,6).reshape(6)
a

array([4, 5, 9, 2, 5, 1], dtype=int32)

In [59]:
a[a % 2 == 1] = -1
a

array([ 4, -1, -1,  2, -1, -1], dtype=int32)

In [62]:
a= np.random.randint(1,50,6).reshape(6)
a

array([28, 38, 20, 39,  9, 33], dtype=int32)

In [66]:
out = np.where(a%2 == 1,-1,a)

In [64]:
a

array([28, 38, 20, 39,  9, 33], dtype=int32)

In [67]:
out

array([28, 38, 20, -1, -1, -1], dtype=int32)

In [69]:
a = np.random.randint(1,50,10)
a

array([47, 33, 25, 24,  2, 14,  4,  1, 14,  7], dtype=int32)

In [70]:
np.sort(a)

array([ 1,  2,  4,  7, 14, 14, 24, 25, 33, 47], dtype=int32)

In [71]:
np.percentile(a,25)

np.float64(4.75)

In [72]:
np.percentile(a,50)

np.float64(14.0)

In [73]:
np.percentile(a,75)

np.float64(24.75)

In [75]:
np.percentile(a,99.8)

np.float64(46.74799999999999)