In [1]:
import numpy as np

In [3]:
arr = np.arange(24).reshape(6,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [4]:
arr[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [6]:
arr1 = np.random.randint(low = 1,high = 100,size = 20).reshape(4,5)
arr1

array([[37, 12, 18, 73, 11],
       [65, 60, 82, 87, 14],
       [73, 97, 35, 47, 57],
       [ 7, 87, 31, 35, 26]], dtype=int32)

In [7]:
arr1>50

array([[False, False, False,  True, False],
       [ True,  True,  True,  True, False],
       [ True,  True, False, False,  True],
       [False,  True, False, False, False]])

In [9]:
#indexing using boolean array 
arr1[(arr1>50) & (arr1%2 != 0)]

array([73, 65, 87, 73, 97, 57, 87], dtype=int32)

In [10]:
arr1[(arr1>50) & (arr1%2 != 0)] = 0

In [11]:
arr1

array([[37, 12, 18,  0, 11],
       [ 0, 60, 82,  0, 14],
       [ 0,  0, 35, 47,  0],
       [ 7,  0, 31, 35, 26]], dtype=int32)