In [20]:
import numpy as np

In [21]:
arr1 = np.arange(24).reshape(6,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [22]:
arr1[2]

array([ 8,  9, 10, 11])

In [23]:
arr1[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [24]:
arr1[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [25]:
arr1[:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [26]:
arr1[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [27]:
arr1[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [28]:
arr1[4:6,2:5]

array([[18, 19],
       [22, 23]])

In [29]:
for i in arr1:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [30]:
for i in np.nditer(arr1):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
