In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])
arr1-arr2

array([-3, -3, -3, -3, -3, -3])

In [3]:
arr1*arr2

array([ 4, 10, 18, 28, 40, 54])

In [4]:
arr1*2

array([ 2,  4,  6,  8, 10, 12])

In [6]:
arr1>3

array([False, False, False,  True,  True,  True])

In [10]:
arr3 = np.arange(6).reshape(2,3)
arr4 = np.arange(6,12).reshape(3,2)

arr3.dot(arr4)


array([[ 28,  31],
       [100, 112]])

In [12]:
arr4.min()

np.int64(6)

In [15]:
arr4.min(axis = 0)

array([6, 7])

In [16]:
arr4.min(axis = 1)

array([ 6,  8, 10])

In [18]:
arr4.sum(axis = 0)

array([24, 27])

In [19]:
arr4.sum(axis = 1)

array([13, 17, 21])

In [20]:
arr4.mean()

np.float64(8.5)

In [21]:
arr4.std()

np.float64(1.707825127659933)

In [22]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [23]:
np.median(arr4)

np.float64(8.5)

In [24]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])