In [1]:
import numpy as np

In [3]:
arr1 = np.arange(24).reshape(6,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [4]:
for i in np.nditer(arr1):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [5]:
arr1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [6]:
arr1.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [11]:
arr2 = np.arange(12,18).reshape(2,3)
arr3 = np.array([0,1,2,3,4,5]).reshape(2,3)
arr2

array([[12, 13, 14],
       [15, 16, 17]])

In [13]:
np.hstack((arr3,arr2))

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [14]:
np.vstack((arr3,arr2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [16]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
np.hsplit(arr3,3)

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [17]:
np.vsplit(arr3,2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]